title: Gertjan's blog
author: gjvdree
email: gertjan@reedev.nl
# social links
twitter_username: GertjanvdRee # DO NOT include the @ character, or else the build will fail!
github_username:  gjvdree # DO NOT include the @ character, or else the build will fail!

# theme
theme: jekyll-theme-tactile

show_excerpts: true # set to false to remove excerpts on the homepage
