title: Divergent thoughts
author: Gertjan van de Ree
email: gertjan@reedev.nl
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my nerdy blog
 
# social links
twitter_username: GertjanvdRee # DO NOT include the @ character, or else the build will fail!
github_username:  gjvdree # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
